
name: Verify
on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Install ImageMagick
        run: |
          sudo wget https://www.imagemagick.org/download/ImageMagick.tar.gz 
          sudo tar xf ImageMagick.tar.gz 
          cd ImageMagick-7*
          sudo ./configure --with-heic=yes 
          sudo make  
          sudo make install
  
      - name: Test HEIC conversion
        run: |
          magick test/fixtures/files/logo.jpg -resize 100x100 output1.png
          magick test/fixtures/files/img.HEIC -resize 100x100 output2.png
