
name: Verify
on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      
      - name: Test HEIC conversion
        run: |
          ls
          convert -version
          convert /logo.jpg -resize 100x100 output1.png
          convert /img.HEIC -resize 100x100 output2.png
