
name: Verify
on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Install libs
        run: |
          sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install build-essential autoconf libtool git-core
          sudo apt-get build-dep imagemagick libmagickcore-dev libde265 libheif
          cd /usr/src/ 
          sudo git clone https://github.com/strukturag/libde265.git  
          sudo git clone https://github.com/strukturag/libheif.git 
          cd libde265/ 
          sudo ./autogen.sh 
          sudo ./configure 
          sudo make  
          sudo make install 
          cd /usr/src/libheif/ 
          sudo ./autogen.sh 
          sudo ./configure 
          sudo make  
          sudo make install 
          cd /usr/src/ 
          
      - name: Install ImageMagick
        run: |
          sudo wget https://www.imagemagick.org/download/ImageMagick.tar.gz 
          sudo tar xf ImageMagick.tar.gz 
          cd ImageMagick-7*
          sudo ./configure --with-heic=yes 
          sudo make  
          sudo make install
          sudo ldconfig
  
      - name: Test HEIC conversion
        run: |
          magick logo.jpg -resize 100x100 output1.png
          magick img.HEIC -resize 100x100 output2.png
